// Generated by scripts/optimize-about.mjs — measured from the coat in the About portrait.
// Do not edit by hand; re-run `npm run optimize:about`.
export const coatPalette = {
  "source": "37fd3e9e-5b4b-4c99-ad27-78e45fd9a349.jpg",
  "coatMedian": "#a9784a",
  "accent": "#a5784e",
  "accentHover": "#b99777",
  "accentRgb": "165, 120, 78",
  "contrastOnBackground": 5.15
} as const;
